[package]
name = "minimal-blockchain"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true, features = ["io-util"] }
serde = { workspace = true }
bincode = { workspace = true }
sha2 = "0.10"
hex = "0.4"
guild-logger = { path = "../guild-logger" }

[dev-dependencies]